<?php

return [
    'firstname'=>[
        'Azad',
        'Aram',
        'Baran',
        'Dara',
        'Dilshad',
        'Dilovan',
        'Hiwa',
        'Hemin',
        'Hawar',
        'Hozan',
        'Karwan',
        'Kawa',
        'Kamiran',
        'Kovan',
        'Sipan',
        'Soran',
        'Sirwan',
        'Şivan',
        'Şerko',
        'Şaho',
        'Rojhat',
        'Rojdar',
        'Renas',
        'Reber',
        'Rezan',
        'Rostam',
        'Bawer',
        'Berzan',
        'Bestun',
        'Bager',
        'Botan',
        'Civan',
        'Ciger',
        'Cemal',
        'Cihan',
        'Delzar',
        'Dilsoz',
        'Diyar',
        'Ferhad',
        'Ferman',
        'Firat',
        'Goran',
        'Gever',
        'Hesen',
        'Hemid',
        'Helbest',
        'Jiyan',
        'Jiyar',
        'Kendal',
        'Lokman',
        'Mazlum',
        'Miran',
        'Merdan',
        'Nawzad',
        'Nihad',
        'Nûbar',
        'Omed',
        'Pêşewa',
        'Qadir',
        'Qubad',
        'Ramyar',
        'Rashin',
        'Salar',
        'Salih',
        'Serbest',
        'Serdar',
        'Tahir',
        'Toran',
        'Welat',
        'Xebat',
        'Xalid',
        'Xelil',
        'Xoshnaw',
        'Yadgar',
        'Yekta',
        'Zana',
        'Zanyar',
        'Zerdeşt',
        'Zinar',
        'Zubêr',
        'Adar',
        'Alan',
        'Arjin',
        'Berxwedan',
        'Caner',
        'Dilxwaz',
        'Erdal',
        'Evar',
        'Harun',
        'Jamal',
        'Mazin',
        'Sefkan',
        'Temo',
        'Xezal',
        'Şiyar',
        'Hêjar',
        'Hêmin',
        'Şivan',
        'Agir'
    ],
    'firstnameEn'=>[
        'azad',
        'aram',
        'baran',
        'dara',
        'dilshad',
        'dilovan',
        'hiwa',
        'hemin',
        'hawar',
        'hozan',
        'karwan',
        'kawa',
        'kamiran',
        'kovan',
        'sipan',
        'soran',
        'sirwan',
        'shivan',
        'sherko',
        'shaho',
        'rojhat',
        'rojdar',
        'renas',
        'reber',
        'rezan',
        'rostam',
        'bawer',
        'berzan',
        'bestun',
        'bager',
        'botan',
        'civan',
        'ciger',
        'cemal',
        'cihan',
        'delzar',
        'dilsoz',
        'diyar',
        'ferhad',
        'ferman',
        'firat',
        'goran',
        'gever',
        'hesen',
        'hemid',
        'helbest',
        'jiyan',
        'jiyar',
        'kendal',
        'lokman',
        'mazlum',
        'miran',
        'merdan',
        'nawzad',
        'nihad',
        'nubar',
        'omed',
        'peshewa',
        'qadir',
        'qubad',
        'ramyar',
        'rashin',
        'salar',
        'salih',
        'serbest',
        'serdar',
        'tahir',
        'toran',
        'welat',
        'xebat',
        'xalid',
        'xelil',
        'xoshnaw',
        'yadgar',
        'yekta',
        'zana',
        'zanyar',
        'zerdest',
        'zinar',
        'zuber',
        'adar',
        'alan',
        'arjin',
        'berxwedan',
        'caner',
        'dilxwaz',
        'erdal',
        'evar',
        'harun',
        'jamal',
        'mazin',
        'sefkan',
        'temo',
        'xezal',
        'shiyar',
        'hejar',
        'agir'
    ],
    'lastname'=>[
        'Barzanî',
        'Talabanî',
        'Herkî',
        'Zêbarî',
        'Dizeyî',
        'Doskî',
        'Sindikî',
        'Mizûrî',
        'Berwarî',
        'Amadî',
        'Zaxoyî',
        'Duhokî',
        'Hewlêrî',
        'Akrayî',
        'Rewandizî',
        'Şaqlawayî',
        'Soranî',
        'Badînî',
        'Hewramî',
        'Botanî',
        'Goyayî',
        'Mameshanî',
        'Beradostî',
        'Pîşdarî',
        'Baneî',
        'Şingalî',
        'Sinjarî',
        'Kobanî',
        'Efrînî',
        'Cizîrî',
        'Mêrdînî',
        'Hekarî',
        'Wanî',
        'Bitlîsî',
        'Dêrsimî',
        'Qersî',
        'Mûşî',
        'Xoshnawî',
        'Reşîdî',
        'Hesenî',
        'Ehmedî',
        'Xelîlî',
        'Mustefayî',
        'Omerî',
        'Mehmûdî',
        'Yûsifî',
        'Îsmaîlî',
        'Silêmanî',
        'Karimî',
        'Qadirî',
        'Salihî',
        'Îbrahîmî',
        'Huseynî',
        'Rehîmî',
        'Hemadî',
        'Nezarî',
        'Fettahî',
        'Sefayî',
        'Ezîzî',
        'Feracî',
        'Tahîrî',
        'Mîranî',
        'Karwanî',
        'Dîlovanî',
        'Rojhanî',
        'Rojbarî',
        'Berxwedanî',
        'Serkanî',
        'Xelatî',
        'Gulanî',
        'Şirwanî',
        'Goranî',
        'Zinarî',
        'Agirî',
        'Bextiyarî',
        'Hejârî',
        'Sipanî',
        'Welatî',
        'Azadî',
        'Renasî',
        'Diyarî',
        'Kendalî',
        'Fermanî',
        'Firatî',
        'Erdalî',
        'Caferî',
        'Nawzadî',
        'Şêxanî',
        'Barzanî',
        'Xalidî',
        'Cemalî',
        'Ferhadî',
        'Nihadî',
        'Salarî',
        'Ramyarî',
        'Qubatî',
        'Lokmanî',
        'Mazlumî',
        'Temoyî'
    ],
    'lastnameEn'=>[
       'barzani',
        'talabani',
        'herki',
        'zebari',
        'dizeyi',
        'doski',
        'sindi',
        'mizuri',
        'berwari',
        'amedi',
        'zakhoi',
        'duhoki',
        'hewleri',
        'akrayi',
        'rawandizi',
        'shaqlawai',
        'sorani',
        'badini',
        'hewrami',
        'botani',
        'goyayi',
        'mameshani',
        'beradosti',
        'pishdari',
        'banei',
        'shingali',
        'sinjari',
        'kobani',
        'afrini',
        'ciziri',
        'merdini',
        'hakkari',
        'vanli',
        'bitlisi',
        'dersimi',
        'qershi',
        'muski',
        'xoshnawi',
        'rashidi',
        'heseni',
        'ehmedi',
        'xelili',
        'mustafayi',
        'omeri',
        'mehmudi',
        'yusifi',
        'ismaili',
        'silemani',
        'karimi',
        'qadiri',
        'salihe',
        'ibrahimi',
        'huseyni',
        'rahimi',
        'hamadi',
        'nazari',
        'fattahi',
        'safayi',
        'azizi',
        'faraji',
        'tahiri',
        'mirani',
        'karwani',
        'dilovani',
        'rojhani',
        'rojbari',
        'berxwedani',
        'serkani',
        'xelati',
        'gulani',
        'shirwani',
        'gorani',
        'zinari',
        'agiri',
        'bextiyari',
        'hejari',
        'sipani',
        'welati',
        'azadi',
        'renasi',
        'diyari',
        'kendali',
        'fermani',
        'firati',
        'erdali',
        'caferi',
        'nawzadi',
        'shexani',
        'xalidi',
        'cemali',
        'ferhadi',
        'nihadi',
        'salari',
        'ramyari',
        'qubadi',
        'lokmani',
        'mazlumi',
        'temoyi'
    ],
    'email'=>['@gmail.com' , '@yahoo.com' , '@hotmail.com' , '@msn.com'],
    'address'=>[
        'Çoman, Kolana Rûbar, Hejmara malê 14',
        'Hewlêr, Kolana Azadî, Hejmara malê 25',
        'Duhok, Kolana Barzanî, Hejmara malê 8',
        'Silêmanî, Kolana Newroz, Hejmara malê 42',
        'Helebce, Kolana Gulan, Hejmara malê 17',
        'Akrê, Kolana Zinar, Hejmara malê 31',
        'Zaxo, Kolana Botan, Hejmara malê 56',
        'Shaqlawa, Kolana Çiya, Hejmara malê 12',
        'Koya, Kolana Hêvî, Hejmara malê 67',
        'Ranya, Kolana Rojhat, Hejmara malê 20',
        'Soran, Kolana Şivan, Hejmara malê 35',
        'Pîrêma, Kolana Bahar, Hejmara malê 49',
        'Barzan, Kolana Welat, Hejmara malê 73',
        'Sêmalka, Kolana Ronahî, Hejmara malê 18',
        'Amedi, Kolana Laleş, Hejmara malê 64',
        'Şêxan, Kolana Xebat, Hejmara malê 29',
        'Dêrelûk, Kolana Avîn, Hejmara malê 91',
        'Soran, Kolana Zêrîn, Hejmara malê 11',
        'Kelar, Kolana Pêşewa, Hejmara malê 38',
        'Xanekîn, Kolana Rêber, Hejmara malê 54',
        'Qaladizê, Kolana Serbest, Hejmara malê 76',
        'Raperîn, Kolana Jiyan, Hejmara malê 23',
        'Kifri, Kolana Dilovan, Hejmara malê 46',
        'Dukan, Kolana Çav, Hejmara malê 15',
        'Bane, Kolana Aram, Hejmara malê 82',
        'Mahabad, Kolana Agir, Hejmara malê 37',
        'Îlam, Kolana Nîştiman, Hejmara malê 69',
        'Wan, Kolana Berxwedan, Hejmara malê 26',
        'Amed, Kolana Hozan, Hejmara malê 93',
        'Mêrdîn, Kolana Diyar, Hejmara malê 44',
        'Cizîr, Kolana Sipan, Hejmara malê 58',
        'Kobanî, Kolana Azadî, Hejmara malê 19',
        'Efrîn, Kolana Gulistan, Hejmara malê 72',
        'Qamişlo, Kolana Rojava, Hejmara malê 34',
        'Dêrik, Kolana Şoreş, Hejmara malê 61',
        'Serêkaniyê, Kolana Baran, Hejmara malê 16',
        'Amûdê, Kolana Nûbar, Hejmara malê 87',
        'Tirbespiyê, Kolana Bawer, Hejmara malê 52',
        'Hesekê, Kolana Helbest, Hejmara malê 28',
        'Reqa, Kolana Xoshnaw, Hejmara malê 75',
        'Sine, Kolana Rêzan, Hejmara malê 39',
        'Urmiyê, Kolana Çinar, Hejmara malê 66',
        'Kirmaşan, Kolana Hêmin, Hejmara malê 21',
        'Dîlok, Kolana Şahîn, Hejmara malê 84',
        'Riha, Kolana Firat, Hejmara malê 47',
        'Elîh, Kolana Kendal, Hejmara malê 13',
        'Mûş, Kolana Xelat, Hejmara malê 59',
        'Bitlîs, Kolana Nergiz, Hejmara malê 33',
        'Hekarî, Kolana Çiyayî, Hejmara malê 70',
        'Dersim, Kolana Baranî, Hejmara malê 24'
    ],
    'country'=>[
        'Kurdistan',
        'Urdun',
        'Lubnan',
        'Emîratên Erebî yên Yekbûyî',
        'Behrên',
        'Misir',
        'Lîbya',
        'Tûnis',
        'Cezayir',
        'Mêrxrib',
        'Sûdan',
        'Etiyopya',
        'Kenya',
        'Nîjerya',
        'Afrîkaya Başûr',
        'Fransa',
        'Almanya',
        'Îrlanda',
        'Îtalya',
        'Îspanya',
        'Portûgal',
        'Belçîka',
        'Holanda',
        'Lûksembûrg',
        'Swîsre',
        'Awûstirya',
        'Swêd',
        'Norwêc',
        'Danîmarka',
        'Fînland',
        'Îslenda',
        'Polonya',
        'Çekya',
        'Slovakya',
        'Macaristan',
        'Romanya',
        'Bulgaristan',
        'Kroatya',
        'Slovenya',
        'Amerîka',
        'Kanada',
        'Meksîk',
        'Brezîlya',
        'Arjantîn',
        'Şîlî',
        'Awustralya',
        'Nû Zelanda',
        'Japonya',
        'Koreya Başûr',
        'Sîngapur',
    ],
    'province'=>[
        'Hewlêr',
        'Silêmanî',
        'Duhok',
        'Helebce',
        'Sine',
        'Kirmaşan',
        'Îlam',
        'Ûrmiyê',
        'Amed',
        'Wan',
        'Hekarî',
        'Şirnex',
        'Agirî',
        'Mûş',
        'Bingol',
        'Bitlîs',
        'Dîlok',
        'Erzîngan',
        'Erzirom',
        'Sêrt',
        'Îdir',
        'Qamişlo',
        'Kobanî',
        'Efrîn',
        'Dêrik',
        'Amûdê',
        'Hesekê',
    ],
    'city'=>[
        'Hewlêr',
        'Silêmanî',
        'Duhok',
        'Helebce',
        'Koyê',
        'Ranye',
        'Soran',
        'Şeqllawa',
        'Akrê',
        'Zaxo',
        'Çemçemal',
        'Kelar',
        'Dukan',
        'Derbendîxan',
        'Pêncwên',
        'Qeledizê',
        'Koysinciq',
        'Mexmûr',
        'Kifri',
        'Çoman',
        'Sîdekan',
        'Herîr',
        'Berdeleş',
        'Raperîn',
        'Qerehençîr',
        'Xaneqîn',
        'Kerkûk',
        'Amed',
        'Wan',
        'Hekarî',
        'Şirnex',
        'Mûş',
        'Bingol',
        'Bitlîs',
        'Agirî',
        'Sêrt',
        'Sine',
        'Kirmaşan',
        'Îlam',
        'Ûrmiyê',
        'Mehabad',
        'Bokan',
        'Seqiz',
        'Merîwan',
        'Pawê',
        'Qamişlo',
        'Kobanî',
        'Efrîn',
        'Hesekê',
        'Amûdê',
    ],
    'telephone'=>[
        '+964 66',  
        '+964 62', 
        '+964 53',  
        '+964 53',  
    ],
    'mobile'=>[
        '+964 750',
        '+964 751',
        '+964 752',
        '+964 753',
        '+964 754',
        '+964 755',
        '+964 756',
        '+964 757',
        '+964 758',
        '+964 759',
        '+964 770',
        '+964 771',
        '+964 772',
        '+964 773',
        '+964 774',
        '+964 775',
        '+964 776',
        '+964 777',
        '+964 778',
        '+964 779',
    ],
    'company'=>[
        'Kar Group',
        'Roj Group',
        'Dana Group',
        'Xoshnaw Group',
        'Newroz Group',
        'Zagros Group',
        'Aras Group',
        'Hewlêr Group',
        'Amanj Group',
        'Kompanyaya Bazirganiya Zagros',
        'Kompanyaya Bazirganiya Kurdistan',
        'Kompanyaya Bazirganiya Hewlêr',
        'Kompanyaya Bazirganiya Silêmanî',
        'Kompanyaya Bazirganiya Duhok',
        'Kompanyaya Bazirganiya Awat',
        'Kompanyaya Bazirganiya Rêbaz',
        'Kompanyaya Bazirganiya Serwer',
        'Kompanyaya Bazirganiya Niştiman',
        'Kompanyaya Bazirganiya Bextiyar',
        'Kompanyaya Avakirina Zagros',
        'Kompanyaya Avakirina Aras',
        'Kompanyaya Avakirina Hewlêr',
        'Kompanyaya Avakirina Avîn',
        'Kompanyaya Avakirina Soran',
        'Kompanyaya Nefta Gazin',
        'Kompanyaya Enerjiya Kurdistan',
        'Kompanyaya Enerjiya Zagros',
        'Kompanyaya Petrolê Kurdistan',
        'Kompanyaya Xizmetguzariya Neftê',
        'Kompanyaya Teknolojiyaya Zagros',
        'Kompanyaya Dijîtala Kurdistan',
        'Kompanyaya Softwareya Hewlêr',
        'Kompanyaya Torê Kurdistan',
        'Kompanyaya Sîstema Nû',
        'Kompanyaya Xwarinê Kurdistan',
        'Kompanyaya Berhemên Zagros',
        'Kompanyaya Avîn Xwarin',
        'Kompanyaya Şîrîniya Hewlêr',
        'Kompanyaya Çandiniya Sêwz',
        'Kompanyaya Geştiyariyê Kurdistan',
        'Kompanyaya Geşt û Gozariya Zagros',
        'Kompanyaya Otêla Hewlêr',
        'Kompanyaya Xizmetguzariya Silêmanî',
        'Kompanyaya Peywendiyan',
        'Kompanyaya Pêşketin',
        'Kompanyaya Asۆ',
        'Kompanyaya Jiyar',
        'Kompanyaya Sirwan',
        'Kompanyaya Halo',
        'Kompanyaya Alton',
    ],
    'job'=>[
        'Mamoste',
        'Mamosteyê zanîngehê',
        'Bijîşk',
        'Perestar',
        'Dermanfiroş',
        'Karmendê tenduristiyê',
        'Karmendê nexweşxaneyê',
        'Endazyar',
        'Endazyariya bajarî',
        'Endazyariya elektrîkê',
        'Endazyariya mekanîk',
        'Endazyariya kompîturê',
        'Endazyariya neftê',
        'Bernameker',
        'Nivîskarê bernameyan',
        'Avakerê webê',
        'Karmendê IT',
        'Dîzaynerê grafîkê',
        'Dîzaynerê UI/UX',
        'Analîstê daneyan',
        'Rêveberê kompanyayê',
        'Rêveberê projeyê',
        'Rêvebirê bazirganiyê',
        'Karmendê hikûmetê',
        'Karmendê sazûmanê',
        'Karmendê bankê',
        'Hesibkar',
        'Karmendê darayî',
        'Bazirgan',
        'Xwediyê kompanyayê',
        'Firoşkar',
        'Bazarpêker',
        'Karmendê firotinê',
        'Karmendê kirînê',
        'Sekreter',
        'Alîkarê rêveber',
        'Parêzer',
        'Dadwer',
        'Rojnamevan',
        'Werger',
        'Polîs',
        'Fermandarê leşkerî',
        'Şofêr',
        'Karkerê kargehê',
        'Karmendê avahîsaziyê',
        'Cotkar',
        'Karmendê çandiniyê',
        'Çêjkar',
        'Xizmetguzarîya otêlê',
        'Karmendê geştiyariyê',
    ],
    'color'=>[
        'Spî',
        'Reş',
        'Sor',
        'Şîn',
        'Kesk',
        'Zer',
        'Qehweyî',
        'Mor',
        'Pemeyî',
        'Narincî',
        'Xwelamêşî',
        'Axirî',
        'Zêrîn',
        'Zîvîn',
        'Bej',
        'Krêmî',
        'Bêjeyî',
        'Avî',
        'Şîna Kal',
        'Şîna Tarî',
        'Keska Kal',
        'Keska Tarî',
        'Sora Tarî',
        'Qehweyiya Tarî',
        'Qehweyiya Kal',
        'Mora Tarî',
        'Mora Kal',
        'Xwelamêşiya Tarî',
        'Xwelamêşiya Kal',
        'Zera Kal',
    ],
    'product'=>[
        'Mobîl',
        'Laptop',
        'Kompîtur',
        'Tablet',
        'Kîbord',
        'Maus',
        'Monîtor',
        'Çapker',
        'Hardî derve',
        'Bîra flash',
        'Televîzyon',
        'Spîker',
        'Hedfon',
        'Şarjker',
        'Kabloya USB',
        'Kamera',
        'Saeta jîr',
        'Powerbank',
        'Ravekera WiFi',
        'Karta bîrê',
        'Firîj',
        'Firîzer',
        'Cilşo',
        'Kuler',
        'Buharî',
        'Oven',
        'Mîkroowêv',
        'Çaysaz',
        'Blender',
        'Carooya elektrîkî',
        'Kanebe',
        'Mêz',
        'Kursî',
        'Kabîne',
        'Text',
        'Dolab',
        'Perde',
        'Fêş',
        'Çiraya malê',
        'Awêne',
        'Kamera',
        'Bors',
        'Saet',
        'Pêlav',
        'Kiras',
        'Pantolon',
        'Kotek',
        'Canta',
        'Çetir',
        'Çavk',
    ],
    'protocol'=>['http' , 'https'],
    'internet'=>['com.krd', 'com', 'krd', 'net', 'edu.krd', 'org', 'gov.krd', 'org.krd', 'co'],
    'word'=>[
        'Azadî',
        'Aştî',
        'Xweşewistî',
        'Heval',
        'Malbat',
        'Mal',
        'Bav',
        'Dayik',
        'Bira',
        'Xwişk',
        'Zarok',
        'Mezin',
        'Jîn',
        'Jiyan',
        'Hêvî',
        'Awat',
        'Xewn',
        'Kar',
        'Zanist',
        'Xwendin',
        'Pirtûk',
        'Qelem',
        'Dibistan',
        'Zanîngeh',
        'Mamoste',
        'Xwendekar',
        'Bazar',
        'Firoşgeh',
        'Kompanya',
        'Pere',
        'Bazirgani',
        'Bajar',
        'Gund',
        'Çiya',
        'Dar',
        'Gul',
        'Av',
        'Rûbar',
        'Derya',
        'Baran',
        'Roj',
        'Heyv',
        'Stêrk',
        'Roj',
        'Şev',
        'Bihar',
        'Havîn',
        'Payîz',
        'Zivistan',
        'Kurdistan',
        'Niştiman',
        'Gel',
        'Ziman',
        'Çand',
        'Dîrok',
        'Huner',
        'Muzîk',
        'Stran',
        'Helbest',
        'Nivîsîn',
        'Wêne',
        'Reng',
        'Bedewî',
        'Karîgerî',
        'Hêz',
        'Serkeftin',
        'Pêşketin',
        'Jêhatî',
        'Ezmûn',
        'Bîrdoz',
        'Dahênan',
        'Teknolojî',
        'Înternet',
        'Kompîtur',
        'Daney',
        'Proje',
        'Sazûman',
        'Hikumet',
        'Yasa',
        'Dad',
        'Maf',
        'Berpirsyarî',
        'Piştgirî',
        'Alîkarî',
        'Hevkari',
        'Rêz',
        'Bawerî',
        'Hêvî',
        'Serbixwebûn',
        'Rê',
        'Derî',
        'Pencere',
        'Çira',
        'Pirtûkxane',
        'Park',
        'Baxçe',
        'Agir',
        'Ax',
        'Ezman'
    ],
    'sentence'=>[
    'Ez her roj hewl didim ku bi xwendin, lêkolîn û fêrbûna tiştên nû zanîna xwe berfireh bikim, ji ber ku bawer dikim ku perwerde bingeha pêşketina kesayetî û civakî ye.',
    'Kurdistan bi dîroka xwe ya kevn, çiyayên bilind, zozanên xweşik û çandeke dewlemend nîşana nasnameyekê ye ku ji nifşekê bo nifşê din hatiye parastin.',
    'Di jiyana rojane de, mirov divê hertim bi dilovanî, rêzgirtin û rastgotinê tevbigere, ji ber ku ev nirx hem têkiliyên mirovan xurt dikin û hem jî civakeke baş ava dikin.',
    'Dema ku mirov armancên xwe diyar dike û bi sebir û karê domdar li ser wan dixebite, ew dikare astengiyên jiyanê derbas bike û bigihîje encamên ku dixwaze.',
    'Malbat ji bo her mirovekî cihê ewle, evîn û piştgiriyê ye, ji ber ku di demên kêfxweş û dijwar de endamên malbatê her tim li cem hev dimînin.',
    'Zimanê Kurdî ne tenê amûrek ji bo ragihandinê ye, lê her weha beşekî girîng ji çand, dîrok û nasnameya gelê Kurd e.',
    'Teknolojî di sedsala nû de guhertineke mezin di jiyana mirovan de çêkiriye û alîkariya me dike ku agahiyan bi lez bigihînin cîhanê.',
    'Mirovên ku ji xwendin û fêrbûnê hez dikin dikarin ramanên xwe pêş bixin û ji bo çareserkirina pirsgirêkên civakê roleke erênî bilîzin.',
    'Dostekî rastîn ew kes e ku di demên dijwar de te tenê nahêle, li kêlekê te dimîne û bi gotinên xwe yên baş hêvî û hêzê dide te.',
    'Xwezaya Kurdistanê bi çiyayên xwe yên bilind, newalên kûr û çavkaniyên avê dîmenên gelek bedew pêşkêşî mêvan û niştecihan dike.',
    'Mamoste ne tenê kesekî ku ders dide, lê kesekî ye ku raman, karakter û paşeroja xwendekaran di avakirina civakeke pêşketî de bandor dike.',
    'Kar û hewldana rojane dikare mirovekî ji qonaxên dijwar derbas bike û rê li ber serkeftinê veke, heke ew bi bawerî û domdarî bixebite.',
    'Huner û muzîk di nav hemû gelan de roleke taybet hene, ji ber ku ew hest, bîranîn û çîrokên mirovan bi awayekî xweşik vediguhêzin.',
    'Dema ku em ji xwezayê re rêz bigirin û çavkaniyên wê baş biparêzin, em dikarin jîngeheke paqijtir û saxlemtir ji nifşên pêşerojê re bihêlin.',
    'Pêşketina civakekê bi zanist, aborî, perwerde û hevkariyê ve girêdayî ye, ji ber ku yekîtiya mirovan hêza sereke ya guhertinê ye.',
    'Mirovên ku bi hêvî û bawerî dijîn di beramberî pirsgirêkên jiyanê de zêdetir berxwedan nîşan didin û bi hêsanî teslîm nabin.',
    'Pirtûkxane cihên girîng ên zanînê ne ku mirov dikare tê de bi xwendina pirtûkan ramanên nû bistîne û têgihiştina xwe berfireh bike.',
    'Bazirganiya rast û bi bawerî dikare derfetên kar zêde bike, aboriyê xurt bike û alîkariya civakê bike ku bi awayekî baştir pêş bikeve.',
    'Her kes di jiyanê de xwedî hêz û karîna taybet e, lê divê ew bi xebat, fêrbûn û baweriya bi xwe vê hêzê pêş bixe.',
    'Dîroka gelan ji bûyerên girîng pêk tê û parastina vê dîrokê alîkariya nifşên nû dike ku nasname û çanda xwe nas bikin.',
    'Rêwîtiya jiyanê tijî ezmûnên cuda ye û her ezmûnek dikare dersên girîng bide mirovan ku wan di avakirina siberojeke baştir de alîkar bike.',
    'Kompîtur, bernamekirin û zanistên teknolojîk di demên me yên îro de bûne amûrên bingehîn ji bo pêşketina kesayetî û aborî.',
    'Hevaltiya rastîn li ser bingehên bawerî, rêz û dilsozî tê avakirin û dikare salên dirêj di nav mirovan de bimîne.',
    'Azadî û dad du nirxên bingehîn in ku civakeke aram û pêşketî li ser wan tê avakirin û pêşdeçûna mirovan pêk tînin.',
    'Mirov divê ji çewtiyên xwe fêr bibe û wan wek ezmûnekê bibîne, ji ber ku her çewtî dikare bibe derfetek ji bo baştirbûnê.',
    'Rêya serkeftinê her tim hêsan nîne, lê kesên ku bi sebir, bawerî û xebata domdar dimeşin dikarin astengiyên mezin derbas bikin û bigihîjin armancên xwe.',
    'Civakeke pêşketî ew civak e ku di navbera endamên xwe de rêz, hevkarî û piştgirî heye û her kes ji bo baştirbûna wê berpirsiyar e.',
    'Xwendekarên ku bi meraq û hezkirina zanînê dixebitin dikarin di warên cuda de pêş bikevin û di paşerojê de bibin kesên bandorker.',
    'Dema ku mirov demê xwe baş birêve dibe û karên xwe bi rêk û pêk dike, ew dikare di jiyana xwe de aramî û serkeftinek zêdetir bi dest bixe.',
    'Çanda Kurdî bi stran, helbest, çîrok û kevneşopiyên xwe dewlemend e û ev taybetmendî dike ku nasnameya gelê Kurd bihêz bimîne.',
    'Mirov dikare bi hînkirina zimanên nû, fêrbûna zanistên cuda û vekirina hişê xwe derfetên nû ji bo pêşketina xwe biafirîne.',
    'Di jiyana profesyonel de, berpirsiyarî û rastbûn du taybetmendiyên girîng in ku dihêlin kesek di karê xwe de baweriya kesên din bi dest bixe.',
    'Dema ku rêveberên baş guh didin ramanên kesên din û biryarên xwe bi dad û rastiyê didin, ew dikarin sazûmanek xurt û serketî ava bikin.',
    'Xwezaya cîhanê bi cureyên cuda yên ajal û nebatan dewlemend e û parastina vê xezîneyê berpirsiyariya hemû mirovan e.',
    'Mirovên ku ji alîkariya kesên din re hez dikin bi kirinên xwe civakê xurt dikin û hesteke baş di navbera mirovan de belav dikin.',
    'Zanist û lêkolîn du hêzên sereke ne ku dihêlin mirov ji sînorên berê derbas bibe û çareseriyên nû ji bo pirsgirêkan bibîne.',
    'Pêwendiyên di navbera mirovan de dema ku li ser bawerî, gotûbêj û rêzgirtinê ava dibin, zêdetir domdar û bihêz dibin.',
    'Muzîka Kurdî bi deng û gotinên xwe hestên gelê Kurd vediguhêze û bîranînên gelek nifşan di nav xwe de diparêze.',
    'Her zarok hewceyê evîn, perwerde û rêberiyê ye ji ber ku şertên baş ên mezinbûnê bandoreke mezin li paşeroja wî dikin.',
    'Pêşketina aborî tenê bi zêdebûna pereyan nayê pîvandin, lê bi çêkirina derfetên kar, pêşxistina zanînê û başkirina jiyanê jî tê dîtin.',
    'Mirovên ku bi plan û armancên zelal dixebitin zêdetir şans hene ku daxwazên xwe pêk bînin û di rêya jiyanê de pêş bikevin.',
    'Dema ku em ji kesên din re rêz nîşan didin û cudahiyên wan qebûl dikin, em civakeke aramtir û hevdu hez dikir ava dikin.',
    'Dîroka mirovan nîşan dide ku her pêşketineke mezin bi hewldan, afirandin û baweriya kesên ku guhertin dixwazin dest pê kiriye.',
    'Baxçe û zeviyên kesk ne tenê cihên xweşik in, lê her weha derfetên baş in ji bo aramî û nêzîkbûna mirovan bi xwezayê re.',
    'Karê komî û hevkariya di navbera kesan de dikare encamên baştir biafirîne, ji ber ku her kes dikare bi zanîn û ezmûna xwe beşdar bibe.',
    'Ramanên nû û dahênanên zanistî gelek caran ji meraq û pirsên biçûk dest pê dikin û di dawiyê de dibe sedema guhertinên mezin.',
    'Jiyana mirovan bi bîranîn, ezmûn û têkiliyên wî yên bi kesên din re tije ye û her qonax dersên taybet hildigire.',
    'Dema ku mirov bi dilpakî û rastî tevbigere, ew dikare baweriya kesên derdora xwe qezenc bike û têkiliyên xwe bihêztir bike.',
    'Serkeftina rastîn ne tenê gihîştina armancan e, lê her weha fêrbûna ji rêya ku mirov di dema gihîştinê de derbas dibe ye.',
    'Pêşeroja civakê bi destê nifşên nû tê avakirin û ji ber vê yekê divê em perwerde, zanist û nirxên baş girîng bihesibînin.',
    ],

    'paragraph'=>[
    'Kurdistan welatekî bi dîrokeke kevn û çandeke dewlemend e ku di nav salan de gelek guherîn dîtine, lê gelê wê hertim hewl daye ku ziman, kevneşopî û nirxên xwe biparêze. Çiyayên bilind, zozanên kesk û çavkaniyên avê yên xweşik taybetmendiyên xwezaya Kurdistanê ne ku gelek kesan dikişînin. Di her deverê Kurdistanê de mirov dikare dîmenên cuda, çandên herêmî û şêwazên jiyanê yên taybet bibîne. Gelê Kurd bi mêvanperweriya xwe navdar e û di nav civakê de rêzgirtin ji bo kesên din nirxeke mezin e. Zimanê Kurdî wek beşekî bingehîn ji nasnameya gelê Kurd hatiye parastin û ji nifşên berê bo nifşên nû hatiye veguhestin. Parastina dîrok û çanda her gelî erkekî girîng e ku pêdivî bi hewldana hemû kesan heye.',
    'Perwerde û zanist bingeha pêşketina her civakê ne, ji ber ku bi zanînê mirov dikare ramanên nû biafirîne û pirsgirêkên jiyanê çareser bike. Dibistan û zanîngeh cihên ku kesên ciwan tê de zanîn, ezmûn û şiyanên nû qezenc dikin in. Mamoste roleke mezin di avakirina kesayetiya xwendekaran de dilîze, ji ber ku ew tenê ders nadin, lê her weha nirxên jiyanê jî hîn dikin. Xwendekarên ku bi hezkirina fêrbûnê dixebitin dikarin di warên cuda de serkeftî bibin û di pêşerojê de bandoreke erênî li civakê bikin. Teknolojî jî di perwerdeyê de derfetên nû çêkiriye û gihîştina agahiyan hêsantir kiriye. Ji ber vê yekê divê civak her tim girîngiyê bide zanist û perwerdeya baş.',
    'Jiyana rojane ya mirovan bi têkiliyên wan ên bi malbat, heval û civakê re girêdayî ye û ev têkilî bandoreke mezin li ser hest û aramiya wan dikin. Malbat cihê ewlehî û evînê ye ku mirov di demên xweş û dijwar de piştgiriya wê hîs dike. Hevalên baş dikarin di rêya jiyanê de bibin alîkar û bi gotinên baş hêvî bidin kesên li derdora xwe. Rêzgirtin, bawerî û dilsozî bingehên têkiliyên saxlem in ku dikarin mirovan nêzîkî hev bikin. Di civakeke baş de her kes divê maf û azadiya kesên din nas bike û bi aramî bi hev re bijî. Bi hevkariyê mirov dikare gelek astengiyan derbas bike û derfetên nû biafirîne.',
    'Teknolojî di serdema me ya îro de roleke mezin di jiyana mirovan de digire û awayê kar, fêrbûn û ragihandinê guherandiye. Kompîtur, înternet û cihên dîtinê yên dîjîtal derfetên mezin ji bo gihîştina agahiyan peyda kirine. Kesên ku zanînên teknolojîk pêş dixin dikarin di bazara karê nû de derfetên baştir bibînin. Lê divê mirov teknolojiyê bi awayekî berpirsiyar bikar bîne û bandorên wê yên erênî û neyînî bizane. Bernamekirin û dahênanên dîjîtal dikarin alîkariya pêşketina aborî û civakî bikin. Paşeroja cîhanê bi lez diguhere û fêrbûna zanînên nû ji bo adaptasyonê pir girîng e.',
    'Xwezaya cîhanê xezîneyeke mezin e ku ji çiyayên bilind, daristanên kesk, deryayan û ajalên cuda pêk tê. Parastina jîngehê berpirsiyariyeke hevpar e ku hemû mirovan divê beşdarî wê bibin. Bikaranîna rast a çavkaniyên xwezayê dikare alîkar be ku jîngeheke paqijtir ji nifşên paşerojê re bimîne. Germbûna cîhanê û kêmbûna çavkaniyên xwezayê pirsgirêkên mezin in ku hewceyê çareseriyên zanistî ne. Her kes dikare bi guhertina hin adetên rojane beşdarî parastina jîngehê bibe. Evîn û rêzgirtina ji bo xwezayê nîşana berpirsiyariya mirovan li hember cîhana ku tê de dijîn e.',
    'Rêwîtiya mirovan di jiyanê de bi gelek ezmûn, hînkirin û bûyerên cuda dagirtî ye ku her yek ji wan dikare kesayet û ramana mirovan biguherîne. Dema ku mirov rastî pirsgirêkan tê, ew dikare ji wan fêr bibe û hêza xwe ya hundirîn zêde bike. Her astengî dikare bibe derfetek ji bo pêşketinê heke mirov bi hêvî û bawerî li ber xwe bide. Kesên ku ji ezmûnên xwe ders digirin di biryardanê de zêdetir jêhatî dibin. Jiyan ne tenê gihîştina armancan e, lê her weha rêya ku mirov di wê de fêr dibe û mezin dibe jî girîng e. Bi vê nêrîna erênî mirov dikare her roj xwe baştir bike.',
    'Aborî yek ji bingehên girîng ên civakekê ye, ji ber ku derfetên kar û çêkirina jiyana baş bi awayekî rasterast bi wê ve girêdayî ne. Kompanyayên ku bi plan û berpirsiyarî dixebitin dikarin derfetên nû ji bo kesên ciwan biafirînin. Bazirganiya rast û pêwendiyên aborî yên bihêz alîkariya pêşketina herêm û welatan dikin. Mirovên ku xwedî ramanên nû ne dikarin projeyên girîng ava bikin û beşdarî guhertinên erênî bibin. Ji bo aboriyeke bihêz pêdivî bi zanist, teknolojî û rêveberiya baş heye. Hevkariya di navbera kes, karsaz û sazûmanan de dikare rêya pêşketinê hêsantir bike.',
    'Huner yek ji awayên herî kevn ên derbirîna hest û ramanên mirovan e ku di nav hemû çandan de cihê taybet heye. Helbest, muzîk, wêne û şano dikarin çîrok û bîranînên civakan biparêzin. Hunermend bi afirandina karên xwe dikarin dîmenek nû ji jiyanê nîşan bidin û kesan bifikirin. Çanda Kurdî bi stran, dengbêjî û helbestên xwe xwedî mîrateyek dewlemend e. Parastina hunerê alîkariya parastina nasname û dîroka gelan dike. Ji ber vê yekê divê civak girîngiyê bide pêşxistina huner û hunermendan.',
    'Rêberî û rêveberiya baş ji bo her sazûmanekê girîng in, ji ber ku biryarên rast dikarin encamên baştir biafirînin. Rêberê baş divê guhdarê ramanên kesên din be û bi dad û rastî hereket bike. Rêveberiya serketî tenê bi fermandarî nayê pîvandin, lê bi afirandina hawîrdoreke ku kes dikarin tê de pêş bikevin jî tê dîtin. Di karê komî de bawerî û hevkarî du faktorên sereke ne ku bandoreke mezin hene. Kesên ku berpirsiyarî digirin divê her tim li ber berjewendiya giştî bifikirin. Bi rêveberiya baş mirov dikare armancên mezin pêk bîne.',
    'Zarok û ciwan paşeroja her civakê ne, ji ber vê yekê perwerde û parastina wan erkeke girîng e. Zarokên ku di hawîrdoreke tijî evîn û piştgiriyê de mezin dibin zêdetir şans hene ku bibin kesên serkeftî. Divê malbat û dibistan bi hev re kar bikin da ku derfetên baş ji bo ciwanan çêbikin. Fêrbûna nirxên wekî rêz, berpirsiyarî û hevkariyê ji temenekî biçûk dest pê dike. Ciwanên xwedî zanîn û bawerî dikarin di avakirina siberojeke baştir de roleke mezin bilîzin. Piştgiriya nifşên nû her tim veberhênanek ji bo pêşerojê ye.'

    ],
];


